services:
  elastic-setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elastic-setup
    volumes:
      - ./config/certs:/usr/share/elasticsearch/config/certs
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true